<script type="text/javascript" src="assets/js/bootstrap.js"></script>
<script type="text/javascript" src="assets/js/owl.carousel.js"></script>
<!--<script type="text/javascript" src="assets/js/slick.js"></script>-->
<script type="text/javascript" src="assets/js/select2.min.js"></script>
<script type="text/javascript" src="assets/js/wow.js"></script>
<script type="text/javascript" src="assets/js/page.js"></script>
<script type="text/javascript" src="assets/js/isotope.pkgd.js"></script>
<script type="text/javascript" src="assets/js/flipster.js"></script>
<script type="text/javascript" src="assets/js/jquery.countdown.js"></script>
<script type="text/javascript" src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js"></script>
<script type="text/javascript" src="assets/js/ion.rangeSlider.js"></script>